<!--

PAGINA DE BIENVENIDA, SE MUESTRA CUANDO EL USUARIO ACCEDE A LA RAIZ DE LA APLICACIÓN

PENDIENTE POR DEFINIR CONTENIDO, POR AHORA SOLO SE MUESTRA EL HEADER Y EL FOOTER

-->

@include('header')

@include('footer')